name: Build lambdas
on:
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    container:
      image: node:${{ matrix.node }}
    defaults:
      run:
        working-directory: ./lambdas

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
=======
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v3.2.0
>>>>>>> main
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn format-check
      - name: Run linter
        run: yarn lint
      - name: Run tests
        id: test
        run: yarn test
      - name: Build distribution
        run: yarn build
      - name: Upload coverage report
<<<<<<< HEAD
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4.4.1
=======
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v31.2
>>>>>>> main
        if: ${{ failure() }}
        with:
          name: coverage-reports
          path: ./**/coverage
          retention-days: 5
